### ISSUE TITLE
rehash(), insert() etc incorrect "noexcept" modifier. result of malloc can return nullptr

### ISSUE THREAD

**Issue by hordi** [ktprime/emhash#1]
After quick-look in the code of hashtable7.hpp...
rehash(), insert() etc functions can't have "noexcept" modifier because:
1.Any new-ctor can throw an exception (NEW_KVALUE etc macro).
2.Need to check result of "malloc" and thow bad_alloc exception if it's nullptr
3.For performance reason (may be - need to check) has sense try to replace combination of "free,malloc" to "realloc"
4.Exceptions unsafe (non-consistent state)

In next function (looks like not only this place, but in anyway) if clone throw an exception (any ctor of Key or Value can do it) we have as minimum the memory leak, as maximum - dtor call missing for group of successfully cloned objects.
    HashMap(const HashMap& other)
    {
        _pairs = (PairT*)malloc((2 + other._num_buckets) * sizeof(PairT) + other._num_buckets / 8 + sizeof(uint64_t));
        clone(other); //THROWN EXCEPTION
    }

5. in the ::clone function instead of std::is_pod it's better to use std::is_trivially_copyable
6.key_eq() should return reference type (not object). Nobody knows how complex that type can be.

**Comment by ktprime** [comment]
thanks for your advice, I will fix them. In order to to compiled by c++ 0x on some gcc lower version(ex 4.6.x) it use some not safe way for point 5.

**Comment by hordi** [comment]
You could use std::is_pod for compiler that doesn't support C++11 and more powerfull function for C++11. But in anyway that code is safe right now.

**Comment by hordi** [comment]
Also currently I see only ::insert and ::insert_unique functions which supports strongly or"const" or "movable&&" parameters. Properly, for good performance, similar function should also accept any combination of "const and &&".

**Comment by ktprime** [comment]
You are right. I need some time to fix the api problem.

**Comment by hordi** [comment]
reserve(uint32_t num_elems) and rehash(uint32_t required_buckets):
This code looks suspicious. If input size is big enough, may be, it'll be in "infinitive cycle".
        **while (num_buckets < required_buckets) { num_buckets *= 2; }**

**Comment by ktprime** [comment]
> reserve(uint32_t num_elems) and rehash(uint32_t required_buckets):
> This code looks suspicious. If input size is big enough, may be, it'll be in "infinitive cycle".
> while (num_buckets < required_buckets) { num_buckets *= 2; }

if hash map the size > 2^31(huge), fix it by change uint64_t num_buckets.

**Comment by ktprime** [comment]
I have fixed some issuses as your point out and some also left.

**Comment by hordi** [comment]
Could you prepare VS project for this bench-project or add standard CMakefile.txt, I have VS compiler on Windows only.

Some remarks...
1.It is wrong to use __cplusplus >= 201103L macro - VS2010 doesn't have is_trivially* etc functions but has that c++ version on.
2.It is wrong to use (_MSC_VER > 1600) - that is IDE version, not actual compiler. It is possible to use VS2019 but project with Platform Toolset VS2010 or SDK7.1. I think, for MSVS compiler need to use some minimal Windows SDK Version, for example, 8.1 is available only in VS compiler that supports C++11 completely.

3.Instead of duplicating functions (::insert  etc) body with different input modifiers it is better to implement one only function like:

`   
    template<typename K, typename V> 
    uint32_t insert_unique(K&& key, V&& value)
    {
        check_expand_need();
        auto bucket = find_unique_bucket(key);
        NEW_KVALUE(std::forward<K>(key), std::forward<V>(value), bucket);
        return bucket;
    }
`

**Comment by ktprime** [comment]
I'll give a CMakefile.txt soon, In fact I also use vs 2017 to bench. 
as a work around you can drag the ebench.cpp to your vs projcet and set include file.

try use clang++ and it's easy be integrated  and used in vs tool.
http://releases.llvm.org/9.0.0/LLVM-9.0.0-win64.exe

**Comment by hordi** [comment]
Take a look this function:
ValueT set_get(const KeyT& key, const ValueT& value)

Next code overwrites current value by the NEW, and returns also NEW value. Expected behavior - return OLD value.
            const ValueT& old_value = GET_VAL(_pairs, bucket);
            GET_VAL(_pairs, bucket) = value;
            return old_value;

Next function (and may be some other with input iterator arithmetic) uses "end - begin" that limited type of input iterators (can't use std::list::iterator for example). It needs to be replaced to std::distance.

```C++
    template <typename Iter>
    void insert_unique(Iter begin, Iter end)
    {
        reserve(end - begin + _num_filled);
        for (; begin != end; ++begin) {
            insert_unique(*begin);
        }
    }
```

**Comment by ktprime** [comment]
other hash map do not suppor insert(key,value), so I have to use emplace to replace it.

**Comment by ktprime** [comment]
the full test code and CMakeLists.txt is in https://github.com/ktprime/emhash/blob/master/hash_bench.zip

**Comment by hordi** [comment]
will run it on 2 PC: XEON & Skylake CPUs... 

About set_get. Are you sure it is good to copy that value every time? Actually, 1 redundant copy, if Value-type is non-trivial it'll be some perf degradation.

Now
```C++
            const ValueT old_value = GET_VAL(_pairs, bucket);
            GET_VAL(_pairs, bucket) = value;
            return old_value;
```
It is better something like this:

```C++
            ValueT old_value(value);
            std::swap( old_value, GET_VAL(_pairs, bucket));
            return old_value;
```

**Comment by ktprime** [comment]
fix issue
