### ISSUE TITLE
Which table is the fastest?

### ISSUE THREAD

**Issue by hitdshu** [ktprime/emhash#12]
Hi,

Very excellent project!

I download your code, and make the comparison between std::unordered_map/robin_hood/unordered_dense.

I only do the benchmark on find elements. Your code is astonishingly fast. All results are with type similar to std::unordered_map<int, int>.

For finding an element in a map with 1000 elements. Here is my result:
unordered_map : 15ns
emhash_table7: 3.6
emhash_table8: 4.2
unordered_dense: 5.6
robin_hood: 7.8

Your implement is the fastest in terms of finding elements with 100% hit. However, which table is the fastest in all your implementations? I only tried table7 and table8.

Best,
Deshun

**Comment by hitdshu** [comment]
I also want to ask another question. How do I support key of the type std::pair<int, int> in your current hash_table7?

**Comment by ktprime** [comment]
speed depends on your case.

for big key-value( sizeof(k+v) >= 24 ) emhash8 (hash_table8.hpp) is good choice,  it's a dense hash map.

if you care about inserting speed or high load factor(>0.95) emhash7 is better.

emhash5 is efficinet for earssion and find hit.

more ressuly as flow
you can try run my bench https://github.com/ktprime/emhash/blob/master/bench/ebench.cpp
g++ -I.. -I../thirdparty -O3 -march=native -DET=1 -std=17 -DHOOD_HASH=1 -DABSL=1 ebench.cpp -o eb

**Comment by hitdshu** [comment]
Thanks for your kind reply.

I'll use your emhash7 in my project as it is both fast at insert and find.

And for key type of std::pair<int, int>, if your emhash7 is the same as std::unordered_map, I think boost::hash_combine might be appropriate here.

Best,
Deshun

**Comment by ktprime** [comment]
my code focus on optimiazing finding hit. 

-------------------------------- function benchmark -----------------------------------------------
erase_50
  64        emhash5                100.0%
  66        emhash6                98.2%
  75        emhash8                85.8%
  99        emhash7                65.5%

erase_reinsert
  86        emhash6                100.0%
  87        emhash5                98.6%
  91        emhash8                94.1%
  96        emhash7                89.4%

find_erase_50
  76        emhash5                100.0%
  82        emhash6                92.7%
  85        emhash7                89.3%
  95        emhash8                79.4%

find_hit_0
  82        emhash8                100.0%
  92        emhash6                88.7%
  94        emhash5                87.1%
  97        emhash7                83.8%

find_hit_100
  83        emhash5                100.0%
  84        emhash7                99.3%
  85        emhash6                98.0%
  97        emhash8                85.8%

find_hit_50
  84        emhash5                100.0%
  85        emhash7                97.7%
  88        emhash6                94.8%
  95        emhash8                87.9%

find_hit_50_erase
  67        emhash8                100.0%
  78        emhash5                86.8%
  95        emhash6                70.9%
  98        emhash7                68.8%

hash_iter
   6        emhash8                100.0%
  26        emhash7                25.5%
  27        emhash6                24.9%
 100        emhash5                6.8%

insert_erase
  76        emhash5                100.0%
  86        emhash6                89.1%
  89        emhash7                86.3%
  96        emhash8                79.4%

insert_find_erase
  33        emhash5                100.0%
  58        emhash8                57.5%
  91        emhash6                36.8%
 100        emhash7                33.7%

insert_high_load
  46        emhash7                100.0%
  53        emhash6                87.7%
  83        emhash5                55.9%
  92        emhash8                50.1%

insert_hit
  79        emhash6                100.0%
  86        emhash7                91.8%
  94        emhash5                84.7%
  94        emhash8                84.1%

insert_l1_cache
  74        emhash7                100.0%
  85        emhash6                87.1%
  87        emhash5                85.0%
  99        emhash8                75.3%

insert_l3_cache
  81        emhash7                100.0%
  85        emhash6                94.7%
  91        emhash5                89.0%
  96        emhash8                84.4%

insert_no_reserve
  68        emhash6                100.0%
  74        emhash7                92.5%
  80        emhash5                85.1%
  97        emhash8                70.7%

multi_small_ife
  78        emhash5                100.0%
  81        emhash6                97.0%
  84        emhash7                92.9%
  98        emhash8                79.7%

======== hash  top1   top2  top3 =======================
      emhash5  1.0  15.0   16
      emhash6 27.0   6.0    0
      emhash7  0.0  14.0   18
      emhash8  7.0   0.0    1
======== hash    score  weigh ==========================
      emhash8    81     95.5%
      emhash7    81     95.5%
      emhash6    84     98.8%
      emhash5    85     100.0%
--------------------------------------------------------------------

**Comment by hitdshu** [comment]
Well, could you explain more about the generated table a bit?

I run your benchmark and got similar output, but I could not understand its concrete meaning...

**Comment by ktprime** [comment]
the following function case **erase_50**:
```
erase_50
  64        emhash5                100.0%
  66        emhash6                98.2%
  75        emhash8                85.8%
  99        emhash7                65.5%
```
emhash5 performance score is 100 (large is better). 

with many rand data cases and the average performace as follow (including many function cases).

```
======== hash    score  weigh ==========================
      emhash8    81     95.5%
      emhash7    81     95.5%
      emhash6    84     98.8%
      emhash5    85     100.0%
```

**Comment by hitdshu** [comment]
Thanks very much for your very kind reply.

Another question. It turns out I also need one hash set.... Does the four hash sets implemented in your code has similar speed? I'll take time to benchmark your hash set as well in this weekend.

Best,
Deshun

**Comment by hitdshu** [comment]
Another question. If I want to cache the table memory across several function calls. Which hash table/hash set is possible? Can I directly clear the table/set at the start of each function call and the memory is still reused?

**Comment by hitdshu** [comment]
> Another question. If I want to cache the table memory across several function calls. Which hash table/hash set is possible? Can I directly clear the table/set at the start of each function call and the memory is still reused?

As an example:

emhash::hash_map<int, int> cache_map;
for (auto i = 0; i < 100; ++i) {
    cache_map.clear();
    // *****other operations
}

Can this cache the memory of the hash_map across the iterations? I.e., is the memory only allocated once if space allowed?

**Comment by ktprime** [comment]
if u want to release hash map memory,  just call shrink_to_fit() or swap it with a empty map.
clear() only removes cache data(call destruction) without memory release.
call reserve() keep memory allocated.

**Comment by hitdshu** [comment]
Thanks for your answers
