### ISSUE TITLE
shrink_to_fit error

### ISSUE THREAD

**Issue by DoThingYo** [ktprime/emhash#16]
Dear author,

Thanks so much for your great library. But I just got an error for "../emhash/hash_table7.hpp:1326: void emhash7::HashMap<KeyT, ValueT, HashT, EqT>::rehash(uint64_t) [with KeyT = int; ValueT = float; HashT = std::hash<int>; EqT = std::equal_to<int>; uint64_t = long unsigned int]: Assertion `buckets < max_size() && buckets > _num_filled' failed." when "shrink_to_fit()" function was calling.

Could you please help me with this problem?

Best regards,
Bob

**Comment by ktprime** [comment]
what's your case? 
  if the size of emhash > (1>>30), it will overflow, you can define EMH_SIZE_TYPE_64BIT before include the head file.
