### ISSUE TITLE
emhash6::HashMap in infinitive loop during adding records (operator[]) on gcc-9.2 compiler

### ISSUE THREAD

**Issue by hordi** [ktprime/emhash#2]
emhash6::HashMap - "infinitive loop" on last gcc compiler using hbench.cpp.

**Comment by ktprime** [comment]
on some platform it'll be hanged compiled by some g++ with -O2, set compile flag with -fno-stirct-aliasing is a work around, it'll be fixed

**Comment by ktprime** [comment]
fixed now
