### ISSUE TITLE
Is there any plan for a release or a tag?

### ISSUE THREAD

**Issue by zhqrbitee** [ktprime/emhash#20]
Hi, 
Is there any plan for a release or a tag? It is hard to know which commit is considered to be a stable version, so it is inconvenient to maintain it as a third-party dependency.

**Comment by ktprime** [comment]
It's a good issiue, I have a plan to make a relase/tag.  
emhash is stable for normal use cases, most commits come from 
benchmark/3rd update(a new benchmark repository) 

btw do you use it in your project? why not use the other hash map?

**Comment by zhqrbitee** [comment]
Sorry for a bit late reply. 
Yes, we have use it in our project and we have internal benchmark with a bunch of hash maps. Our use case requires high frequency insertion (we guarantee the inserted key is unique each time), find and erase and your one gives the best performance.

**Comment by ktprime** [comment]
try use insert_unique(10% fast than emplace) if inserted key is unique.   
if The key is integral and care about finding hit performance, set marco EMH_FIND_HIT for better find.
I've added a new featue in emhash5 optimaiztion for small hash_map.

![image](https://user-images.githubusercontent.com/1461362/206408312-25d99df2-65ad-4f4a-baa8-e8e04535810b.png)
