### ISSUE TITLE
Add benchmark of hashmap implemented in other lang

### ISSUE THREAD

**Issue by sundy-li** [ktprime/emhash#22]
Hello, we have a hashmap implemented in rust.  Maybe we could bench it using `cxx` ?

https://github.com/datafuselabs/databend/tree/main/src/common/hashtable

**Comment by ktprime** [comment]
I have never benchmark any rust hash map,  if u want to add new hash map into this benchmark, it's interface must 
implement like c++ std::unordered_map.
