### ISSUE TITLE
Might be an issue of the code.

### ISSUE THREAD

**Issue by hitdshu** [ktprime/emhash#24]
Hi,

Very excellent projects. I used your map in my numerical visual-inertial odometry project, and it works much better than std::unordered_map.

However, I encountered one problem. I use Eigen library to perform matrix calculations. And when I enable -march=native in GCC, the emhash7::HashMap<int, Eigen::Matrix4d> will emit segmentation fault.

I found that Eigen will assume an aligned memory if -march=native is enabled. And for C++17 and after, Eigen will take care of the alignment, and we need to do nothing. https://eigen.tuxfamily.org/dox/group__TopicStlContainers.html

Use std::unordered_map<int, Eigen::Matrix4d> or ankerl::unordered_dense::unordered_map<int, Eigen::Matrix4d> works for me. I think it might because your code does not use an allocator?

Anyway, it's a very tedious problem. It might not be your problem, but I decide to report it to you.

Best,
Deshun

**Comment by ktprime** [comment]
Can you reproduce it or offer any coredump stack?
only C "malloc/free" memory function used in emhash without using std::allocator.
 Maybe I should add std::allocator to emash to fix the alignment issiue or implement aligned_malloc

**Comment by ktprime** [comment]
emhash8 can be a good choice without alignment issiue.

**Comment by hitdshu** [comment]
Okay, I will provide an example this weekend, as I  have to do other things in work days.

**Comment by ktprime** [comment]
```
I have some way which can fix your issiue .
1. change your code emhash7::HashMap<int, Eigen::Matrix4d> to  emhash7::HashMap<**int64_t**, Eigen::Matrix4d> 

2.  change the source code in emhash7
template <typename First, typename Second>
 struct entry **alignas(16?32)** {

```

**Comment by hitdshu** [comment]
Well, sorry for the late reply.

Turns out, there are many interesting to do in holidays...

Thanks for your advice, and I'll provide you an example befor 1/30/2023.

Deshun

**Comment by hitdshu** [comment]
Well, I wrote a demo program, please check it.
[map_eigen_test.zip](https://github.com/ktprime/emhash/files/10535289/map_eigen_test.zip)

**Comment by ktprime** [comment]
I can reproduce it now, the problem is align issue by malloc(default 16 byte align).
but in your test code, Eigen::Matrix4d need 32 bytes align.

https://stackoverflow.com/questions/46301140/32-byte-aligned-allocator-for-aligned-eigen-map
 
To fix this issiue emhash need some redesign. (allocator in constructor or use
aligned_malloc function)

ex:
 _pairs = (PairT*) new ((std::align_val_t) 32) char[AllocSize(_num_buckets)];

**Comment by ktprime** [comment]
this is a fix version

**Comment by hitdshu** [comment]
Thanks for your timely reply. It works. Thanks.
