### ISSUE TITLE
Which HashSet is fastest?

### ISSUE THREAD

**Issue by qdztxc** [ktprime/emhash#26]
This is no doc mentioned about HashSet.
What's the difference between hash_set2 hash_set3 hash_set4 and hash_set8? Which is the fastest?

Besides Is there a mapping relationship between HashMap and HashSet?

**Comment by ktprime** [comment]
run the benchmark code on your evn( compiles on emhash/bench dir) https://github.com/ktprime/emhash/blob/master/bench/sbench.cpp

/mnt/d/emhash-master/bench$ make BF=1 SW=1 std=17
/mnt/d/emhash-master/bench$ ./sb

![image](https://user-images.githubusercontent.com/1461362/216961286-0601b5b1-1087-455f-9ab0-8b3ff23cae18.png)

some result look like following (high is better).
if you want to more benchmark results(hash + key), try to set different marco and retset it.

**Comment by ktprime** [comment]
readme updated, it offers some advice on how to choose emhash.
