### ISSUE TITLE
hash_table6.hpp uses own hash-function for Integral types even if assigned different one (EMHASH_FIBONACCI_HASH = 1)

### ISSUE THREAD

**Issue by hordi** [ktprime/emhash#3]
Actually, it is impossible to assign any custom hash-function if EMHASH_FIBONACCI_HASH is defined.
Can't say does it good or no, but a bit unexpected...

**Comment by ktprime** [comment]
most time fibonacci hash is a very fast and efficient hash function and it's used in many other hash map.

another marco EMHASH_SAFE_HASH is also a safe guard if the input hash is highly collisioned. but default all marco is not defined.
