### ISSUE TITLE
请问有实现原理的介绍吗？

### ISSUE THREAD

**Issue by yuhui-xie** [ktprime/emhash#33]
试了一下很棒，比stl的哈希要快很多。
我想了解一下源码是什么实现的，但被一堆位运算绕进去了。
请问emhash有什么相关的原理介绍吗？

**Comment by ktprime** [comment]
emhash没有采用太深的算法实现，与stl最大不同是采用扁平单一数组存储节点数据，通常称为**flat hash map**，类似
vector那样一次扩容(rehash)后插入不再需要频繁的申请内存，内存性能比stl 好很多。

数据hash冲突与stl解决策略（**开链表**）不同，每个节点除了key,value 之外还有额外辅组冲突索引 index，用于记录当前相同hash冲突的下一个节点，也就是使用下标模拟链表方式解决冲突。

hash冲突算法上采用多种混合策略查找**空节点**，先在**主节点**附近线性探测，然后结合二次探测和随机探测，可以做到非常高的内存使用率

代码hash_table5.hpp 是基础实现，其他几个版本是变种有不同的使用场景。
可以先看这个简化版本 https://github.com/emilk/emilib/blob/master/emilib/hash_map.hpp （单纯**线性探测**）
参照一下lua 语言核心结构hash map 冲突解决思路（**主桶不可侵占思想**）
大致明白原理之后再看容易理解 


```
struct entry
{
  Key key
  int index
  Value val
}
```

**Comment by yuhui-xie** [comment]
感谢

**Comment by yuhui-xie** [comment]
简化版还是比较好理解，但是变种还是对我有点难。。。
可以帮忙解释一下hash_set7.cpp中对iterator初始化这个操作是什么意思吗？
`        void init()
        {
            _from = (_bucket / SIZE_BIT) * SIZE_BIT;
            if (_bucket < _map->bucket_count()) {
                _bmask = *(size_t*)((size_t*)_map->_bitmask + _from / SIZE_BIT);
                _bmask |= (1ull << _bucket % SIZE_BIT) - 1;
                _bmask = ~_bmask;
            } else {
                _bmask = 0;
            }
        }`

**Comment by yuhui-xie** [comment]
请问hash_table7.cpp中的这几个变量设置的用途是什么呢？
iterator中的_from和_bmask，HashMap中的_bitmask以及_mask。
没有太看懂迭代器寻找下一个元素的逻辑。。。求教

**Comment by ktprime** [comment]
hashmap 数组中很多空位，使用位数组_bitmask记录空位信息

为了迭代过程中查找加速（跳过空位），使用cpu 位操作指令__builtin_ctzll（_BitScanForward64），
该指令可快速知道64位整数中最高bit 1位置。
每64位作为一个缓存分别记录当前迭代过程中group位置 _from，以及64bit对应的整数 _bmask。
原理不复杂，需要理解一下。

**Comment by yuhui-xie** [comment]
> _bitmask

噢我大致看懂了，不过` _bmask = ~*(size_t*)((size_t*)_map->_bitmask + (_from += SIZE_BIT) / SIZE_BIT);`这里，从bitmask数组中取出了一个空的group后，为什么要先取位反呢？

**Comment by yuhui-xie** [comment]
> hashmap 数组中很多空位，使用位数组_bitmask记录空位信息，每bit对应节点数组_pairs是否为空。
> 
> 为了迭代过程中查找加速（跳过空位），使用cpu 位操作指令__builtin_ctzll（_BitScanForward64）， 该指令可快速知道64位整数中最高bit 1位置。 每64位作为一个缓存，记录当前迭代过程中group位置 _from，以及64bit对应的整数 _bmask。 迭代过程的核心代码如下，根据当前_bmask 知道下一bit 1位置，也就是非空位（有效数据节点）
> 
> ```
>     //迭代性能远超其他hashmap实现, 最快迭代是hash_table8.hpp 里面紧凑数组，无空位。
>      void goto_next_element()
>        {
>            _bmask &= _bmask - 1; //迭代后将最后bit 清0 
>            if (_bmask != 0) {
>                _bucket = _from + CTZ(_bmask);
>                return;
>            }
>           //如果整个_bmask  为0，查找下一个空group
>            do {
>                _bmask = ~*(size_t*)((size_t*)_map->_bitmask + (_from += SIZE_BIT) / SIZE_BIT);
>            } while (_bmask == 0);
> 
>            _bucket = _from + CTZ(_bmask);
>        }
> ```
> 
> 原理不复杂，需要理解一下。

噢我大致看懂了，不过` _bmask = ~*(size_t*)((size_t*)_map->_bitmask + (_from += SIZE_BIT) / SIZE_BIT);`这里，从bitmask数组中取出了下一个group后，为什么要先取位反呢？

**Comment by yuhui-xie** [comment]
> 



> > hashmap 数组中很多空位，使用位数组_bitmask记录空位信息，每bit对应节点数组_pairs是否为空。
> > 为了迭代过程中查找加速（跳过空位），使用cpu 位操作指令__builtin_ctzll（_BitScanForward64）， 该指令可快速知道64位整数中最高bit 1位置。 每64位作为一个缓存，记录当前迭代过程中group位置 _from，以及64bit对应的整数 _bmask。 迭代过程的核心代码如下，根据当前_bmask 知道下一bit 1位置，也就是非空位（有效数据节点）
> > ```
> >     //迭代性能远超其他hashmap实现, 最快迭代是hash_table8.hpp 里面紧凑数组，无空位。
> >      void goto_next_element()
> >        {
> >            _bmask &= _bmask - 1; //迭代后将最后bit 清0 
> >            if (_bmask != 0) {
> >                _bucket = _from + CTZ(_bmask);
> >                return;
> >            }
> >           //如果整个_bmask  为0，查找下一个空group
> >            do {
> >                _bmask = ~*(size_t*)((size_t*)_map->_bitmask + (_from += SIZE_BIT) / SIZE_BIT);
> >            } while (_bmask == 0);
> > 
> >            _bucket = _from + CTZ(_bmask);
> >        }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 原理不复杂，需要理解一下。
> 
> 噢我大致看懂了，不过` _bmask = ~*(size_t*)((size_t*)_map->_bitmask + (_from += SIZE_BIT) / SIZE_BIT);`这里，从bitmask数组中取出了下一个group后，为什么要先取位反呢？

噢我好像看懂了，我看到你后面rehash的时候有用这几个宏
`
#define EMH_SET(bucket)                _bitmask[bucket / MASK_BIT] &= ~(EMH_MASK(bucket))
#define EMH_CLS(bucket)                _bitmask[bucket / MASK_BIT] |= EMH_MASK(bucket)   
#define EMH_EMPTY(bitmask, bucket)     (_bitmask[bucket / MASK_BIT] & (EMH_MASK(bucket))) != 0  
`
所以实际上新加一个东西进来后，是把对应的bit置0，清除则是置1，恰好和查找时反过来的，所以这里置反吗...？
这样设计的原因是可以用CTZ去快速找对应位置吗?
ps:
这边为什么用的是MASK_BIT（32位），而迭代器跑的时候用的是SIZE_BIT（64位）呢？

**Comment by yuhui-xie** [comment]
> > 
> 
> > > hashmap 数组中很多空位，使用位数组_bitmask记录空位信息，每bit对应节点数组_pairs是否为空。
> > > 为了迭代过程中查找加速（跳过空位），使用cpu 位操作指令__builtin_ctzll（_BitScanForward64）， 该指令可快速知道64位整数中最高bit 1位置。 每64位作为一个缓存，记录当前迭代过程中group位置 _from，以及64bit对应的整数 _bmask。 迭代过程的核心代码如下，根据当前_bmask 知道下一bit 1位置，也就是非空位（有效数据节点）
> > > ```
> > >     //迭代性能远超其他hashmap实现, 最快迭代是hash_table8.hpp 里面紧凑数组，无空位。
> > >      void goto_next_element()
> > >        {
> > >            _bmask &= _bmask - 1; //迭代后将最后bit 清0 
> > >            if (_bmask != 0) {
> > >                _bucket = _from + CTZ(_bmask);
> > >                return;
> > >            }
> > >           //如果整个_bmask  为0，查找下一个空group
> > >            do {
> > >                _bmask = ~*(size_t*)((size_t*)_map->_bitmask + (_from += SIZE_BIT) / SIZE_BIT);
> > >            } while (_bmask == 0);
> > > 
> > >            _bucket = _from + CTZ(_bmask);
> > >        }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 原理不复杂，需要理解一下。
> > 
> > 
> > 噢我大致看懂了，不过` _bmask = ~*(size_t*)((size_t*)_map->_bitmask + (_from += SIZE_BIT) / SIZE_BIT);`这里，从bitmask数组中取出了下一个group后，为什么要先取位反呢？
> 
> 噢我好像看懂了，我看到你后面rehash的时候有用这几个宏 `#define EMH_SET(bucket) _bitmask[bucket / MASK_BIT] &= ~(EMH_MASK(bucket)) #define EMH_CLS(bucket) _bitmask[bucket / MASK_BIT] |= EMH_MASK(bucket) #define EMH_EMPTY(bitmask, bucket) (_bitmask[bucket / MASK_BIT] & (EMH_MASK(bucket))) != 0 ` 所以实际上新加一个东西进来后，是把对应的bit置0，清除则是置1，恰好和查找时反过来的，所以这里置反吗...？ 这样设计的原因是可以用CTZ去快速找对应位置吗? ps: 这边为什么用的是MASK_BIT（32位），而迭代器跑的时候用的是SIZE_BIT（64位）呢？

似乎后面的find_empty_bucket中，又是以8位操作bitmask的了，我也没太看懂这个函数的操作流程。。。还想请教一下

**Comment by ktprime** [comment]
存贮 _bitmask 使用32位整数操作，迭代过程使用64位操作
查找空位find_empty_bucket为了byte对齐使用8位操作（查找第一次），比如当前index 是3，前面的3bit 无效清0
后面查找都是基于64位。

整个hashmap最核心的冲突解决方案如下，空位快速查找
```
    // key is not in this map. Find a place to put it.
    size_type find_empty_bucket(const size_type bucket_from, const size_type main_bucket)
    {
#if EMH_ITER_SAFE
        const auto boset = bucket_from % 8;
        auto* const align = (uint8_t*)_bitmask + bucket_from / 8;(void)main_bucket; 为了对齐，index 所在第一个byte 需要部分bit位清0
        size_t bmask; memcpy(&bmask, align + 0, sizeof(bmask)); bmask >>= boset;// bmask |= ((size_t)align[8] << (SIZE_BIT - boset));
        if (EMH_LIKELY(bmask != 0))
            return bucket_from + CTZ(bmask);
#else
        const auto boset  = main_bucket % 8;
        auto* const align = (uint8_t*)_bitmask + main_bucket / 8; (void)bucket_from;
        const size_t bmask  = (*(size_t*)(align) >> boset);// & 0xF0F0F0F0FF0FF0FFull;//
        if (EMH_LIKELY(bmask != 0))
            return main_bucket + CTZ(bmask);
#endif
```

**Comment by yuhui-xie** [comment]
> _bitmask 使用32位整数数组存贮，迭代和查找中使用64位(size_t的位数 **依赖平台和编译器**)操作，两者相互独立。
> 
> 查找空位find_empty_bucket为了第一个byte对齐使用8位操作（**查找起始byte**），比如当前index 是3，前面的3bit 无效清0，后面查找都是基于64位。
> 
> 比如说从当前位置bucket_from = 17开始查找空位，17 % 8 = 2 余 1， 那么第三个byte开始的第一位必须清0（8位操作）， 从3-10连续8个bye 构成一个64 bit整数，可以使用ctz 快速查找。
> 
> ```
>    整个hashmap最核心的冲突解决方案如下，空位快速查找
>     // key is not in this map. Find a place to put it.
>     size_type find_empty_bucket(const size_type bucket_from, const size_type main_bucket)
>     {
> #if EMH_ITER_SAFE
>         const auto boset = bucket_from % 8;
>         auto* const align = (uint8_t*)_bitmask + bucket_from / 8;(void)main_bucket; 为了对齐，bucket_from（**bit位索引**） 所在第一个byte 需要部分bit位清0
>         size_t bmask; memcpy(&bmask, align + 0, sizeof(bmask)); bmask >>= boset;// bmask |= ((size_t)align[8] << (SIZE_BIT - boset));
>         if (EMH_LIKELY(bmask != 0))
>             return bucket_from + CTZ(bmask);
> #else
>         const auto boset  = main_bucket % 8;
>         auto* const align = (uint8_t*)_bitmask + main_bucket / 8; (void)bucket_from;
>         const size_t bmask  = (*(size_t*)(align) >> boset);// & 0xF0F0F0F0FF0FF0FFull;//
>         if (EMH_LIKELY(bmask != 0))
>             return main_bucket + CTZ(bmask);
> #endif
> ```

噢那我看懂了，所以整个find_unique_bucket的策略是：
1. 看一下main_bucket所划分到的8位区间内有没有空位
2. 没有的话，搜最后一次存放空桶的地方_last，看看该桶内（64bit）有没有位置
3. 没有的话，再看看_last加一半桶的数目的地方，看看该桶内（64bit）有没有位置
4. 没有的话，_last+1，然后重复2~3
大概是这样吗？

BTW，大佬你为啥设计了一个这样的流程去找空位呢？

**Comment by ktprime** [comment]
当数组快满，这个查找空位算法超级高效，一次能查找64个连续位置（一般线性查找只能一个个遍历, swsiss table 可以查找16个，高负载下性能插入性能指数下降），

当设置最大load factor 0.99 ( 大多其他实现都在最高负载因子load factor 0.5-0.8左右，)其性能依旧刚刚的，
可以测试一下，大量节省内存同时性能还不下降。
我有一个性能测试，负载因子0.99左右 插入与删除，我的hashmap基本遥遥领先。

位运算是最基本的运算，不要被一点点复杂度吓怕。

**Comment by ktprime** [comment]
文件其实列出了查找的复杂度，hash冲突本身是符合泊松分布的
```
// From
// NUMBER OF PROBES / LOOKUP       Successful            Unsuccessful
// Quadratic collision resolution  1 - ln(1-L) - L/2     1/(1-L) - L - ln(1-L)
// Linear collision resolution     [1+1/(1-L)]/2         [1+1/(1-L)2]/2
// separator chain resolution      1 + L / 2             exp(-L) + L

// -- enlarge_factor --           0.10  0.50  0.60  0.75  0.80  0.90  0.99
// QUADRATIC COLLISION RES.
//    probes/successful lookup    1.05  1.44  1.62  2.01  2.21  2.85  5.11
//    probes/unsuccessful lookup  1.11  2.19  2.82  4.64  5.81  11.4  103.6
// LINEAR COLLISION RES.
//    probes/successful lookup    1.06  1.5   1.75  2.5   3.0   5.5   50.5
//    probes/unsuccessful lookup  1.12  2.5   3.6   8.5   13.0  50.0
// SEPARATE CHAN RES.
//    probes/successful lookup    1.05  1.25  1.3   1.25  1.4   1.45  1.50
//    probes/unsuccessful lookup  1.00  1.11  1.15  1.22  1.25  1.31  1.37
//    clacul/unsuccessful lookup  1.01  1.25  1.36, 1.56, 1.64, 1.81, 1.97

    under random hashCodes, the frequency of nodes in bins follows a Poisson
distribution(http://en.wikipedia.org/wiki/Poisson_distribution) with a parameter of about 0.5
on average for the default resizing threshold of 0.75, although with a large variance because
of resizing granularity. Ignoring variance, the expected occurrences of list size k are
(exp(-0.5) * pow(0.5, k)/factorial(k)). The first values are:
0: 0.60653066
1: 0.30326533
2: 0.07581633
3: 0.01263606
4: 0.00157952
5: 0.00015795
6: 0.00001316
7: 0.00000094
8: 0.00000006
```

**Comment by yuhui-xie** [comment]
> 文件起始列出了各种查找算法的平均复杂度，hash冲突本身是符合泊松分布的 负载0.99的时候，线性探测平均需要50次迭代才能找到非空位置，我的算法不到2次
> 
> ```
> // From
> // NUMBER OF PROBES / LOOKUP       Successful            Unsuccessful
> // Quadratic collision resolution  1 - ln(1-L) - L/2     1/(1-L) - L - ln(1-L)
> // Linear collision resolution     [1+1/(1-L)]/2         [1+1/(1-L)2]/2
> // separator chain resolution      1 + L / 2             exp(-L) + L
> 
> // -- enlarge_factor --           0.10  0.50  0.60  0.75  0.80  0.90  0.99
> // QUADRATIC COLLISION RES.
> //    probes/successful lookup    1.05  1.44  1.62  2.01  2.21  2.85  5.11
> //    probes/unsuccessful lookup  1.11  2.19  2.82  4.64  5.81  11.4  103.6
> // LINEAR COLLISION RES.
> //    probes/successful lookup    1.06  1.5   1.75  2.5   3.0   5.5   50.5
> //    probes/unsuccessful lookup  1.12  2.5   3.6   8.5   13.0  50.0
> // SEPARATE CHAN RES.
> //    probes/successful lookup    1.05  1.25  1.3   1.25  1.4   1.45  1.50
> //    probes/unsuccessful lookup  1.00  1.11  1.15  1.22  1.25  1.31  1.37
> //    clacul/unsuccessful lookup  1.01  1.25  1.36, 1.56, 1.64, 1.81, 1.97
> 
>     under random hashCodes, the frequency of nodes in bins follows a Poisson
> distribution(http://en.wikipedia.org/wiki/Poisson_distribution) with a parameter of about 0.5
> on average for the default resizing threshold of 0.75, although with a large variance because
> of resizing granularity. Ignoring variance, the expected occurrences of list size k are
> (exp(-0.5) * pow(0.5, k)/factorial(k)). The first values are:
> 0: 0.60653066
> 1: 0.30326533
> 2: 0.07581633
> 3: 0.01263606
> 4: 0.00157952
> 5: 0.00015795
> 6: 0.00001316
> 7: 0.00000094
> 8: 0.00000006
> ```

感谢，我基本上看懂了这个code。不过还有俩小问题想问一下，
1.有一些编译的宏对应什么作用吗？像EMH_EXT，EMH_ITER_SAFE。
2.还有rehash的时候，分配内存的区间大概像
        //                [0-_num_buckets]:pairs，分配单元是sizeof(PairT)
        //                [EPACK_SIZE]:epack，分配单元是sizeof(PairT)
        //                [(num_buckets + 7) / 8 ]：_bitmask，分配单元是sizeof(uint32_t)
        //                [ BIT_PACK ]: bit_pack
bit_pack中似乎是用来存上次分配的last变量？但epack是用来干啥的呢？

**Comment by ktprime** [comment]
_bitmask 位数必须大于pairs 分配空间个数 _num_buckets
查找和迭代到尾部可能出现bit位所在group数组溢出，所以需多分配内存防止溢出，也就是EPACK_SIZE和BIT_PACK 主要作用（至于大小并无意义，不低于当前设置数值就行）

```
    static size_t AllocSize(uint64_t num_buckets)
    {
        return (num_buckets + EPACK_SIZE) * sizeof(PairT) + (num_buckets + 7) / 8 + BIT_PACK;
    }
```

_bitmask 内存在_pairs后面一起分配。
其实际内存是 **(num_buckets + 7) / 8 + BIT_PACK**;
EMH_EXT                           , 扩展接口，非标准api
EMH_ITER_SAFE                 对齐作用，防止非x86上内存不对齐访问溢出
大多宏默认不开启，不需要关注，都是某些特殊场合使用

**Comment by ktprime** [comment]
你可以关注一下hash_table8.hpp, 算法实现和emhash7 有较大不同，
使用场景有些差异，另外我在优化另外一个基于
> [google swiss table](https://github.com/ktprime/emhash/blob/master/thirdparty/emilib/emilib2o.hpp)
 实现 , 性能你可以测试一下有惊喜。

**Comment by yuhui-xie** [comment]
> 可以关注一下hash_table8.hpp, 算法实现和emhash7 有较大不

哈哈好，感谢!!
