### ISSUE TITLE
Shadow warnings on hash_table8.hpp

### ISSUE THREAD

**Issue by zufuliu** [ktprime/emhash#42]
See https://github.com/ninja-build/ninja/issues/2531, there are shadow warnings when using MSVC `/W4` or GCC/Clang `-Wshadow=local`:

first one inside `find_filled_bucket()`:
https://github.com/ktprime/emhash/blob/afd962a68047f864e29063a33649c0b108741f8c/hash_table8.hpp#L1325-L1337

second one inside `find_filled_slot()`:
https://github.com/ktprime/emhash/blob/afd962a68047f864e29063a33649c0b108741f8c/hash_table8.hpp#L1360-L1371

maybe the inner `slot` could be renamed to `eslot` (as in `find_or_allocate()`) or something else:
https://github.com/ktprime/emhash/blob/afd962a68047f864e29063a33649c0b108741f8c/hash_table8.hpp#L1494-L1509

**Comment by ktprime** [comment]
thanks, I have fixed the issues in lastest version.

**Comment by zufuliu** [comment]
Thanks.
